require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.1.3
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
