version: '0.1'

template: mos
locale: en
compile:
  runs: 2

document:
  klass:
    name: article
    size: 9pt

  paper:
    dimensions:
      width: 119mm
      height: 158mm

    margin:
      top: 10mm
      bottom: 5mm
      left: 12mm
      right: 0mm

    margin_notes:
      placement: left
      width: 10mm
      separation: 1.9mm

planner:
  parameters:
    hand: left
    time_format: 24

    start_date: 2024, January
    end_date: 2024, December
    weekday_start: Monday

  objects:
    little_calendar:
      with_week_numbers: true
      week_number_placement: right

  sections:
    - title:
        enabled: true
        parameters:
          name: 2024

    - annual:
        enabled: true
        parameters:
          months_per_page: 6
          months_per_row: 2

