version: '0.1'

template: mos
locale: en
compile:
  runs: 2

document:
  klass:
    name: article
    size: 9pt

  #  fonts:
  #    roman: Georgia
  #    sans_serif: PT Sans
  #    monospace: PT Mono

  paper:
    dimensions:
      width: 119mm
      height: 158mm

    margin:
      top: 10mm
      bottom: 5mm
      left: 12mm
      right: 5mm

    margin_notes:
      placement: left
      width: 10mm
      separation: 1.9mm

planner:
  parameters:
    time_format: 24

    start_date: 2024, January
    end_date: 2024, June
    weekday_start: Monday

    header_separation: 1mm

  objects:
    little_calendar:
      with_week_numbers: true
      week_number_placement: right
      week_vertical_line: true
      width: 5cm
      vertical_stretch: 1.3
      underline_weekdays: true
      upperline_weekdays: true

    quarters_navigation:
      vertical_stretch: 2

    months_navigation:
      vertical_stretch: 2

  placements:
    side_navigation:
      - quarters_navigation
      - 5mm
      - months_navigation

    heading:
      - function: page_name
        position: "@{}l"
      - function: empty_cell_filler
        position: X
      - function: top_navigation

  sections:
    - title:
        enabled: true
        parameters:
          name: 2024

    - annual:
        enabled: true
        parameters:
          months_per_page: 6
          months_per_row: 2
