version: '0.1'

template: typst_mos
locale: en

document:
  layout:
    dimensions:
      width: 119mm
      height: 158mm

    margin:
      top: 10mm
      bottom: 0mm
      left: 0mm
      right: 5mm

  text:
    size: 10pt

planner:
  parameters:
    time_format: 24

    start_date: 2024, January
    end_date: 2024, December
    weekday_start: Monday

  objects:
    mos_nav:
      width: 10mm
      inset: 2mm
      rotate: 90deg
      reverse_array_internals: false
      reverse_arrays: false

    heading:
      height: 9mm
      inset: 3mm

    little_calendar:
      with_week_numbers: true
      week_number_placement: left
      inset: 1.5mm
      underline_weekdays: true
      sideline_week_numbers: true

  sections:
    - title:
        enabled: true
        parameters:
          name: 2024

    - annual:
        enabled: true
        parameters:
          months_per_page: 6
          months_per_row: 2

#    - quarterly:
#        enabled: true
