version: '0.1'

template: typst_mos
locale: en

document:
  layout:
    dimensions:
      width: 119mm
      height: 158mm

    margin:
      top: 10mm
      bottom: 0mm
      left: 0mm
      right: 5mm

  text:
    size: 10pt

planner:
  parameters:
    time_format: 24

    start_date: 2024, January
    end_date: 2024, December
    weekday_start: Monday

    heading_size: 16pt
    pattern: dotted

  objects:
    mos_nav:
      width: 10mm
      inset: 2mm
      rotate: 90deg
      reverse_array_internals: false
      reverse_arrays: false

    heading:
      height: 10mm
      bottom_pad: 3mm

    little_calendar:
      with_week_numbers: true
      week_number_placement: left
      inset: 1.5mm
      underline_weekdays: true
      sideline_week_numbers: true

    large_calendar:
      with_week_numbers: true
      week_number_placement: right
      weekday_names: short
      heading_height: 6mm
      week_row_height: 20mm
      week_cell_rotate: 90deg

  sections:
    - title:
        enabled: true
        parameters:
          name: 2024
          font_size: 48pt

    - annual:
        enabled: true
        parameters:
          months_per_page: 6
          months_per_row: 2

    - quarterly:
        enabled: true
        parameters:
          months_width: 4.3cm
          gap_width: 5mm
          reverse_columns: false

    - monthly:
        enabled: true
        parameters:
          gap_width: 5mm

    - weekly:
        enabled: true
        parameters:
          first_row_height: 8mm
          rest_row_height: 9mm

    - daily:
        enabled: true
        parameters:
          schedule_from_hour: 8
          schedule_to_hour: 19
          schedule_trailing_30min: true
          enable_little_calendar: false

          gap_width: 2mm
          priorities_number: 5

          notes_height: 4.1cm
          personal_notes_height: 100%
